services:
  s3:
    image: localstack/localstack:s3-latest
    ports:
      - "${S3_PORT:-4566}:4566"
    environment:
      - AWS_REGION=${S3_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-test}
    restart: on-failure:3

  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT:-25060}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-devdogs}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure:3

  mysql-dev:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure:3

  atlas:
    image: arigaio/atlas:latest-alpine
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-devdogs}
    depends_on:
      mysql:
        condition: service_healthy
      mysql-dev:
        condition: service_healthy
    volumes:
      - ./migrations/:/migrations:ro
    command: >
      schema clean
        -u "mysql://root:password@mysql-dev:3306/dev" 
        --auto-approve
